# Generated by Django 4.1.7 on 2023-04-12 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("netbox_secretstore", "0005_alter_secret_created_alter_secret_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secret",
            name="custom_field_data",
            field=models.JSONField(
                blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="secretrole",
            name="custom_field_data",
            field=models.JSONField(
                blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder
            ),
        ),
        migrations.AlterField(
            model_name="userkey",
            name="user",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_key_secretstore",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
