# Generated by Django 3.2.9 on 2021-12-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_secretstore', '0005_secretsgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secret',
            options={'ordering': ('name', 'pk')},
        ),
        migrations.AddField(
            model_name='secretsgroup',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='secrets', to='netbox_secretstore.secretrole'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together={('assigned_object_type', 'assigned_object_id', 'name')},
        ),
        migrations.RemoveField(
            model_name='secret',
            name='role',
        ),
    ]
